//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Validation.Core.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Validation.Core.Messages.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token format is invalid..
        /// </summary>
        internal static string AccessToken_Invalid {
            get {
                return ResourceManager.GetString("AccessToken_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string is not a valid Base64-encoded value..
        /// </summary>
        internal static string Base64_Invalid {
            get {
                return ResourceManager.GetString("Base64_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be equal to &apos;{0}&apos;..
        /// </summary>
        internal static string ConstantValue {
            get {
                return ResourceManager.GetString("ConstantValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit card number is invalid..
        /// </summary>
        internal static string CreditCard_Invalid {
            get {
                return ResourceManager.GetString("CreditCard_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency code is invalid or unsupported..
        /// </summary>
        internal static string Currency_Invalid {
            get {
                return ResourceManager.GetString("Currency_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be a business day (Monday to Friday)..
        /// </summary>
        internal static string Date_BusinessDay {
            get {
                return ResourceManager.GetString("Date_BusinessDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be in the future..
        /// </summary>
        internal static string Date_Future {
            get {
                return ResourceManager.GetString("Date_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The date cannot be in the future..
        /// </summary>
        internal static string Date_InFuture {
            get {
                return ResourceManager.GetString("Date_InFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date cannot be in the past..
        /// </summary>
        internal static string Date_InPast {
            get {
                return ResourceManager.GetString("Date_InPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be in a leap year..
        /// </summary>
        internal static string Date_LeapYear {
            get {
                return ResourceManager.GetString("Date_LeapYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a date without time..
        /// </summary>
        internal static string Date_Only {
            get {
                return ResourceManager.GetString("Date_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be in the past..
        /// </summary>
        internal static string Date_Past {
            get {
                return ResourceManager.GetString("Date_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be marked as UTC..
        /// </summary>
        internal static string Date_Utc {
            get {
                return ResourceManager.GetString("Date_Utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be on a weekday (Monday to Friday)..
        /// </summary>
        internal static string Date_Weekday {
            get {
                return ResourceManager.GetString("Date_Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be on a weekend (Saturday or Sunday)..
        /// </summary>
        internal static string Date_Weekend {
            get {
                return ResourceManager.GetString("Date_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before or equal to end date..
        /// </summary>
        internal static string DateRange_StartAfterEnd {
            get {
                return ResourceManager.GetString("DateRange_StartAfterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number exceeds allowed precision or scale..
        /// </summary>
        internal static string Decimal_PrecisionExceeded {
            get {
                return ResourceManager.GetString("Decimal_PrecisionExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always invalid for test purposes..
        /// </summary>
        internal static string Dev_AlwaysInvalid {
            get {
                return ResourceManager.GetString("Dev_AlwaysInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always valid..
        /// </summary>
        internal static string Dev_AlwaysValid {
            get {
                return ResourceManager.GetString("Dev_AlwaysValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address..
        /// </summary>
        internal static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected value is not a valid option..
        /// </summary>
        internal static string Enum_Invalid {
            get {
                return ResourceManager.GetString("Enum_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file: size or format not allowed..
        /// </summary>
        internal static string File_Invalid {
            get {
                return ResourceManager.GetString("File_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} cannot be empty..
        /// </summary>
        internal static string Guid_Empty {
            get {
                return ResourceManager.GetString("Guid_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a valid hexadecimal string..
        /// </summary>
        internal static string Hex_Invalid {
            get {
                return ResourceManager.GetString("Hex_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IBAN number is invalid..
        /// </summary>
        internal static string IBAN_Invalid {
            get {
                return ResourceManager.GetString("IBAN_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP address format is invalid..
        /// </summary>
        internal static string IpAddress_Invalid {
            get {
                return ResourceManager.GetString("IpAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a valid JSON string..
        /// </summary>
        internal static string Json_Invalid {
            get {
                return ResourceManager.GetString("Json_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid culture code (e.g. en-US)..
        /// </summary>
        internal static string Localization_InvalidCulture {
            get {
                return ResourceManager.GetString("Localization_InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid language tag (e.g. en-US, tr, fr-FR)..
        /// </summary>
        internal static string Localization_InvalidLanguageTag {
            get {
                return ResourceManager.GetString("Localization_InvalidLanguageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid time zone ID..
        /// </summary>
        internal static string Localization_InvalidTimeZone {
            get {
                return ResourceManager.GetString("Localization_InvalidTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must satisfy a comparison rule with another property..
        /// </summary>
        internal static string Logic_CompareWithOther {
            get {
                return ResourceManager.GetString("Logic_CompareWithOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required when {0} is populated..
        /// </summary>
        internal static string Logic_ConditionalRequired {
            get {
                return ResourceManager.GetString("Logic_ConditionalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required when {0} is &apos;{1}&apos;..
        /// </summary>
        internal static string Logic_ConditionalRequiredWithValue {
            get {
                return ResourceManager.GetString("Logic_ConditionalRequiredWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be empty under certain conditions..
        /// </summary>
        internal static string Logic_DisallowedIf {
            get {
                return ResourceManager.GetString("Logic_DisallowedIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be equal to {0}..
        /// </summary>
        internal static string Logic_EqualToOtherProperty {
            get {
                return ResourceManager.GetString("Logic_EqualToOtherProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one of the following fields must be set: {0}..
        /// </summary>
        internal static string Logic_MutuallyExclusiveProperties {
            get {
                return ResourceManager.GetString("Logic_MutuallyExclusiveProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must not be equal to {0}..
        /// </summary>
        internal static string Logic_NotEqualToOtherProperty {
            get {
                return ResourceManager.GetString("Logic_NotEqualToOtherProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required under certain conditions..
        /// </summary>
        internal static string Logic_RequiredIf {
            get {
                return ResourceManager.GetString("Logic_RequiredIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be null..
        /// </summary>
        internal static string MustBeNull {
            get {
                return ResourceManager.GetString("MustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must not be null..
        /// </summary>
        internal static string MustNotBeNull {
            get {
                return ResourceManager.GetString("MustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The national ID number is invalid..
        /// </summary>
        internal static string NationalId_Invalid {
            get {
                return ResourceManager.GetString("NationalId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid domain name..
        /// </summary>
        internal static string Network_DomainName {
            get {
                return ResourceManager.GetString("Network_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid hostname with port..
        /// </summary>
        internal static string Network_HostnameWithPort {
            get {
                return ResourceManager.GetString("Network_HostnameWithPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid IPv6 address..
        /// </summary>
        internal static string Network_IPv6Address {
            get {
                return ResourceManager.GetString("Network_IPv6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be divisible by {0}..
        /// </summary>
        internal static string Number_DivisibleBy {
            get {
                return ResourceManager.GetString("Number_DivisibleBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be even..
        /// </summary>
        internal static string Number_Even {
            get {
                return ResourceManager.GetString("Number_Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must have at most {0} digits..
        /// </summary>
        internal static string Number_MaxDigits {
            get {
                return ResourceManager.GetString("Number_MaxDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must have at least {0} digits..
        /// </summary>
        internal static string Number_MinDigits {
            get {
                return ResourceManager.GetString("Number_MinDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be a multiple of {0}..
        /// </summary>
        internal static string Number_MultipleOf {
            get {
                return ResourceManager.GetString("Number_MultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be zero..
        /// </summary>
        internal static string Number_NotZero {
            get {
                return ResourceManager.GetString("Number_NotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be odd..
        /// </summary>
        internal static string Number_Odd {
            get {
                return ResourceManager.GetString("Number_Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a percentage between 0 and 100..
        /// </summary>
        internal static string Number_PercentageRange {
            get {
                return ResourceManager.GetString("Number_PercentageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be a power of two..
        /// </summary>
        internal static string Number_PowerOfTwo {
            get {
                return ResourceManager.GetString("Number_PowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be a prime..
        /// </summary>
        internal static string Number_Prime {
            get {
                return ResourceManager.GetString("Number_Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be ≥ 1..
        /// </summary>
        internal static string Pagination_PageNumber {
            get {
                return ResourceManager.GetString("Pagination_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be between 1 and 100..
        /// </summary>
        internal static string Pagination_PageSize {
            get {
                return ResourceManager.GetString("Pagination_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        internal static string Password_NumberRequired {
            get {
                return ResourceManager.GetString("Password_NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one symbol..
        /// </summary>
        internal static string Password_SymbolRequired {
            get {
                return ResourceManager.GetString("Password_SymbolRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        internal static string Password_UppercaseRequired {
            get {
                return ResourceManager.GetString("Password_UppercaseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must include upper/lowercase letters, numbers, special characters, and be at least {minLength} characters long..
        /// </summary>
        internal static string Password_Weak {
            get {
                return ResourceManager.GetString("Password_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number format is invalid..
        /// </summary>
        internal static string Phone_Invalid {
            get {
                return ResourceManager.GetString("Phone_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid Turkish mobile phone number..
        /// </summary>
        internal static string Phone_TurkishMobile {
            get {
                return ResourceManager.GetString("Phone_TurkishMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The postal code format is invalid..
        /// </summary>
        internal static string PostalCode_Invalid {
            get {
                return ResourceManager.GetString("PostalCode_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value does not match the required format..
        /// </summary>
        internal static string Regex_Invalid {
            get {
                return ResourceManager.GetString("Regex_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input must be in a valid encrypted format..
        /// </summary>
        internal static string Security_Encrypted {
            get {
                return ResourceManager.GetString("Security_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must not contain invalid characters..
        /// </summary>
        internal static string Security_InvalidFileName {
            get {
                return ResourceManager.GetString("Security_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must not contain HTML tags..
        /// </summary>
        internal static string Security_NoHtml {
            get {
                return ResourceManager.GetString("Security_NoHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must not contain special Unicode symbols or emoji..
        /// </summary>
        internal static string Security_NoUnicodeSymbols {
            get {
                return ResourceManager.GetString("Security_NoUnicodeSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long and contain a letter, number, and symbol..
        /// </summary>
        internal static string Security_PasswordComplexity {
            get {
                return ResourceManager.GetString("Security_PasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input must be safe against SQL injection..
        /// </summary>
        internal static string Security_SqlInjectionSafe {
            get {
                return ResourceManager.GetString("Security_SqlInjectionSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input must not contain potential XSS content..
        /// </summary>
        internal static string Security_XssSafe {
            get {
                return ResourceManager.GetString("Security_XssSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a valid slug (lowercase letters, numbers, and dashes only)..
        /// </summary>
        internal static string Slug_Invalid {
            get {
                return ResourceManager.GetString("Slug_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters and numbers are allowed..
        /// </summary>
        internal static string String_AlphaNumericOnly {
            get {
                return ResourceManager.GetString("String_AlphaNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must be in camelCase format (e.g. exampleText)..
        /// </summary>
        internal static string String_CamelCase {
            get {
                return ResourceManager.GetString("String_CamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid country code (ISO 3166-1 alpha-2)..
        /// </summary>
        internal static string String_CountryCode {
            get {
                return ResourceManager.GetString("String_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid currency code (ISO 4217)..
        /// </summary>
        internal static string String_CurrencyCode {
            get {
                return ResourceManager.GetString("String_CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must end with the required suffix..
        /// </summary>
        internal static string String_EndsWith {
            get {
                return ResourceManager.GetString("String_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid hex color code (e.g. #FFF or #FFFFFF)..
        /// </summary>
        internal static string String_HexColor {
            get {
                return ResourceManager.GetString("String_HexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid hostname..
        /// </summary>
        internal static string String_Hostname {
            get {
                return ResourceManager.GetString("String_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid JWT token..
        /// </summary>
        internal static string String_JwtToken {
            get {
                return ResourceManager.GetString("String_JwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must be in kebab-case format (e.g. example-text)..
        /// </summary>
        internal static string String_KebabCase {
            get {
                return ResourceManager.GetString("String_KebabCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid language code (ISO 639-1)..
        /// </summary>
        internal static string String_LanguageCode {
            get {
                return ResourceManager.GetString("String_LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must be entirely lowercase..
        /// </summary>
        internal static string String_Lowercase {
            get {
                return ResourceManager.GetString("String_Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid MAC address..
        /// </summary>
        internal static string String_MacAddress {
            get {
                return ResourceManager.GetString("String_MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid MIME type (e.g. image/png)..
        /// </summary>
        internal static string String_MimeType {
            get {
                return ResourceManager.GetString("String_MimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not contain special characters..
        /// </summary>
        internal static string String_NoSpecialCharacters {
            get {
                return ResourceManager.GetString("String_NoSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not contain any whitespace characters..
        /// </summary>
        internal static string String_NoWhitespace {
            get {
                return ResourceManager.GetString("String_NoWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must contain only letters..
        /// </summary>
        internal static string String_OnlyLetters {
            get {
                return ResourceManager.GetString("String_OnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not empty, must contain only letters and spaces..
        /// </summary>
        internal static string String_OnlyLetters_Optional {
            get {
                return ResourceManager.GetString("String_OnlyLetters_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must be in PascalCase format (e.g. ExampleText)..
        /// </summary>
        internal static string String_PascalCase {
            get {
                return ResourceManager.GetString("String_PascalCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must contain at least one special character..
        /// </summary>
        internal static string String_SpecialCharRequired {
            get {
                return ResourceManager.GetString("String_SpecialCharRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The value must start with the required prefix..
        /// </summary>
        internal static string String_StartsWith {
            get {
                return ResourceManager.GetString("String_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must start with an uppercase letter..
        /// </summary>
        internal static string String_StartsWithUppercase {
            get {
                return ResourceManager.GetString("String_StartsWithUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty or whitespace..
        /// </summary>
        internal static string String_TrimmedEmpty {
            get {
                return ResourceManager.GetString("String_TrimmedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must be entirely uppercase..
        /// </summary>
        internal static string String_Uppercase {
            get {
                return ResourceManager.GetString("String_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid version format (e.g. 1.0.0)..
        /// </summary>
        internal static string String_Version {
            get {
                return ResourceManager.GetString("String_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time must be between {0} and {1}..
        /// </summary>
        internal static string Time_Range {
            get {
                return ResourceManager.GetString("Time_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid Instagram URL..
        /// </summary>
        internal static string Url_Instagram {
            get {
                return ResourceManager.GetString("Url_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL format is invalid. Only HTTP and HTTPS URLs are allowed..
        /// </summary>
        internal static string Url_Invalid {
            get {
                return ResourceManager.GetString("Url_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid YouTube URL..
        /// </summary>
        internal static string Url_YouTube {
            get {
                return ResourceManager.GetString("Url_YouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a valid XML string..
        /// </summary>
        internal static string Xml_Invalid {
            get {
                return ResourceManager.GetString("Xml_Invalid", resourceCulture);
            }
        }
    }
}
